### ISSUE TITLE
New user not able to access ERP after installing LMS.

### ISSUE THREAD

**Issue by ganureddy** [frappe/lms#992] opened 2024-08-26 13:00 UTC
new use not able to access ERPNext system, After Install of LMS in existing ERPNext System, 
Error showing, mentioned below  

Traceback (most recent call last):
  File "apps/frappe/frappe/www/app.py", line 27, in get_context
    boot = frappe.sessions.get()
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/sessions.py", line 140, in get
    bootinfo = get_bootinfo()
               ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/boot.py", line 75, in get_bootinfo
    bootinfo.notification_settings = get_notification_settings()
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/boot.py", line 401, in get_notification_settings
    return frappe.get_cached_doc("Notification Settings", frappe.session.user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1207, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1333, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 85, in get_doc
    return controller(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 172, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 645, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: Notification Settings admin@brihaspathi.com not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 523, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
    data = self.run_pymodule_method("get_context")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 223, in run_pymodule_method
    return method(self.context)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/www/app.py", line 29, in get_context
    raise frappe.SessionBootFailed from e
frappe.exceptions.SessionBootFailed

**Comment by geverit4** [comment] 2024-08-27 14:37
This is a duplicate of https://github.com/frappe/lms/issues/991. 

Good to see I'm not the only one.

**Comment by pateljannat** [comment] 2024-09-03 17:12
This issue was fixed with https://github.com/frappe/lms/pull/994

**Closed by pateljannat** 2024-09-03 17:12 UTC
Labels: bug

**Comment by ganureddy** [comment] 2024-09-22 22:52
Thank you
