### ISSUE TITLE
when i tried to login with student in to the live class invitation link its shows too many redirections.

### ISSUE THREAD

**Issue by nnilnuwan** [frappe/lms#591] opened 2023-08-16 08:28 UTC
Hi i have intergrade the zoom , google and google calendar API in the LMS system, when i create a live class and save it its automatically sync with google calendar and it looks everything is working perfectly,but when i tried to login with student in the invitation link its show too many redirections. This is the link "https://visiontech.frappe.cloud/courses/introduction-to-erp/learn/1.1 " what should i do now? Its only comes when i try with student user

**Comment by pateljannat** [comment] 2023-08-17 09:19
@nnilnuwan I saw your site and couldn't find any upcoming classes on the website. From where did you create the live class?  Also which invitation link did you try as a student?

**Comment by nnilnuwan** [comment] 2023-08-17 10:48
Oh thanks man, i got fixed that issue

**Comment by pateljannat** [comment] 2023-08-17 15:15
@nnilnuwan if the issue is fixed, can you close this issue?

**Closed** 2024-01-23 10:42 UTC
Labels: bug
