### ISSUE TITLE
[UX] Enhance LMS Quiz by linking LMS Quiz Questions, enable end user to import & manage questions easily.

### ISSUE THREAD

**Issue by asharamseervi** [frappe/lms#444] opened 2022-12-12 06:35 UTC
**Is your feature request related to a problem? Please describe.**
Quiz play an important role in LMS, and crucial part of quiz is, every quiz having sometimes 100 or 100+ questions! 100+ questions managing with present LMS workflow isn't seem feasible.

**Describe the solution you'd like**
At present, LMS Quiz Question are mapped under Table rather than Linking them from Child DocType. Just Linking and Enabling Importing LMS Quiz Question through Import will greatly enhance User Experience of using LMS Quiz.

**Additional context**
We may enhance Questions having their Unique Identity, this will enable to map same question under multiple Quiz's.

**Comment by pateljannat** [comment] 2023-09-12 13:10
Duplicate of #553

**Closed by pateljannat** 2023-09-12 13:10 UTC
