### ISSUE TITLE
Assignment Submission Deadline

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#848] opened 2024-05-29 07:18 UTC
is this possible to have Submission Deadline?
![image](https://github.com/frappe/lms/assets/62122640/9d9c7a7f-a879-4474-b631-69350d30e5f8)

After deadline system will block the user from submission assignment?

**Comment by pateljannat** [comment] 2024-06-07 06:10
Duplicate of #465

**Closed by pateljannat** 2024-06-07 06:10 UTC
